Create a didcomm pickup client javascript client component
ADORSYS-GIS/didcomm-messaging-clients-utilities pull request #7
Opened 2024-11-07 15:49 UTC by Tekum-Emmanuella

PR introduces functions for constructing and securely sending DIDComm pickup requests, delivery requests, and message receipts. It includes encryption, message packing, and unpacking to enhance secure communication for a pickup-client javascript-client

2024-11-11 14:12 UTC, Blindspot22 approved these changes
LGTM :rocket:

2024-11-13 15:25 UTC, Christiantyemele requested changes
Please go through the reviews here they are also repeating in your ticket

2024-11-14 11:34 UTC, Christiantyemele requested changes

2024-11-14 11:34 UTC, Christiantyemele commented on libs/message-handler/src/index.ts
> +});
What is this file for

2024-11-14 11:34 UTC, Christiantyemele commented on libs/message-handler/src/pickup.test.ts
> +  });
Remove the console logs here use expects instead

2024-11-14 11:34 UTC, Christiantyemele commented on libs/message-handler/tsconfig.node.json
>  }
including the src directory is enough here 
```suggestion
  "include": ["src"]
}
```

2024-11-15 13:58 UTC, chendiblessing approved these changes

2024-11-19 14:37 UTC, Christiantyemele approved these changes

2024-11-19 14:39 UTC, merged